let SWAGGER_JSON_URL = '';//url json

const CUSTOM_API_SERVER = process.env.NODE_ENV === 'development';
const CUSTOM_API_HOST = '';//site:port
const CUSTOM_API_PROTOCOL = '';
if(CUSTOM_API_SERVER) {
    SWAGGER_JSON_URL =  `${CUSTOM_API_PROTOCOL}://${CUSTOM_API_HOST}${SWAGGER_JSON_URL}`;
}

export {
    SWAGGER_JSON_URL,
    CUSTOM_API_SERVER,
    CUSTOM_API_HOST,
    CUSTOM_API_PROTOCOL,
}